# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: People
    url: people
    weight: 20
  - name: Research
    url: prjojects
    weight: 30
  - name: Publications
    url: publications
    weight: 40
  - name: News
    url: post
    weight: 50
  - name: Perspective
    url: perspective
    weight: 60
